# Input data
resolution: 512
age_min: 20
age_max: 70
use_realimg: True
# Training hyperparameters
batch_size: 8
epochs: 48
iter_per_epoch: 5000
device: 'cuda'
# Optimizer parameters
optimizer: 'ranger'
lr: 0.0001
beta_1: 0.95
beta_2: 0.999
weight_decay: 0
# Learning rate scheduler
step_size: 10
gamma: 0.1
# Tensorboard log options
image_save_iter: 100
log_iter: 10
# Network setting
use_fs_encoder: False
use_fs_encoder_v2: False
fs_stride: 2
pretrained_weight_for_fs: False
enc_resolution: 256
enc_residual: False
truncation_psi: 1
use_noise: True
randomize_noise: False      # If generator use a different random noise at each time of generating a image from z
# Loss setting
use_parsing_net: True
multi_layer_idloss: True
real_image_as_image_loss: True
feature_match_loss: False
feature_match_loss_G: False
use_random_noise: True
optimize_on_z: False
multiscale_lpips: True
MODEL:
  backbone: "big_resnet"
  g_cond_mtd: "W/O"
  apply_g_sn: True
  apply_d_sn: True
  apply_attn: True
  attn_g_loc: [4]
  attn_d_loc: [1]
  z_dim: 120
  g_shared_dim: 128
  g_conv_dim: 96
  d_conv_dim: 96
  apply_g_ema: True
  g_ema_decay: 0.9999
  g_ema_start: 20000
# Loss weight
w:
  l1: 0
  l2: 1
  lpips: 0.8
  id: 0.1
  landmark: 0
  f_recon: 0
  recip: 0
  dist: 0